name: MasterScheduledCI
on:
  schedule:
    - cron: "0 2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        env:
          REACT_APP_TESTING_TRUE: "false"
          REACT_APP_CLIENT_ID: ${{secrets.NAVOTAR_CLIENT_ID}}
          REACT_APP_HOME_DIRECTORY: ${{secrets.HOME_DIRECTORY}}
        run: |
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.USERNAME}}
          git remote set-url origin https://${{secrets.REPO_TOKEN}}@github.com/${{secrets.USERNAME}}/cars-ridewithjax.git
          npm run deploy:gh-pages
